[**KRITIK AGARWAL 19BBTCS067**](https://github.com/Kritik007)

***DAP Lab Exp.No.4***

Demonstrate the usage of numpy libraries

In [1]:
import numpy as np

#### Creating ndarrays



In [2]:
# generate some random data
data = np.random.randn(2, 3)
data

array([[-0.71743415, -1.90053641, -0.0862186 ],
       [ 0.80863996, -0.23353389,  0.51979667]])

In [3]:
data1 = [6, 7.5, 8, 0, 1]

In [4]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
#Nested Sequences will be converted into multidimensional array
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.empty((2,3,2))

array([[[2.05050840e-316, 2.57353024e-316],
        [3.95252517e-323, 2.57353024e-316],
        [3.95252517e-323, 2.57353024e-316]],

       [[4.44659081e-323, 0.00000000e+000],
        [2.57355554e-316, 2.57355554e-316],
        [2.57355554e-316, 0.00000000e+000]]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Data Types for ndarrays

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [17]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

#### Arithmetic with NumPy Arrays

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [20]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [24]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [25]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [26]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [27]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### Basic Indexing and Slicing

In [28]:
arr = np.arange(10)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

5

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
arr[5:8] = 50

In [33]:
arr

array([ 0,  1,  2,  3,  4, 50, 50, 50,  8,  9])

In [34]:
arr_slice = arr[5:8]

In [35]:
arr_slice

array([50, 50, 50])

In [36]:
arr_slice[1] = 12345

In [37]:
arr

array([    0,     1,     2,     3,     4,    50, 12345,    50,     8,
           9])

In [38]:
arr_slice[:] = 64

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [40]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[0][2]

3

In [43]:
arr2d[0,2]

3

In [44]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [45]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
old_values = arr3d[0].copy()

In [48]:
arr3d[0] = 42

In [49]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0] = old_values

In [51]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[1, 0]

array([7, 8, 9])

In [53]:
x = arr3d[1]

In [54]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
x[0]

array([7, 8, 9])

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr2d[1, :2]

array([4, 5])

In [62]:
arr2d[:2, 2]

array([3, 6])

In [63]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [64]:
arr2d[:2, 1:] = 0

In [65]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### Boolean Indexing

In [66]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [67]:
data = np.random.randn(7, 4)

In [68]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [69]:
data

array([[-1.7954001 , -0.27238636,  0.26087237,  0.51739584],
       [-0.22170597,  0.69652897, -0.76271219, -0.4202649 ],
       [ 0.40017537,  0.56459636,  0.82344516, -0.88931561],
       [-0.55276083, -0.66219038,  1.51469514,  0.74176921],
       [-0.91520788,  1.16605257,  2.3109382 ,  1.24915827],
       [ 0.51929941,  1.298917  , -1.18915305, -1.07543908],
       [ 0.02639373,  0.91449301, -1.52633874,  0.7044852 ]])

In [70]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [71]:
data[names == 'Bob']

array([[-1.7954001 , -0.27238636,  0.26087237,  0.51739584],
       [-0.55276083, -0.66219038,  1.51469514,  0.74176921]])

In [72]:
data[names == 'Bob', 2:]

array([[0.26087237, 0.51739584],
       [1.51469514, 0.74176921]])

#### Fancy Indexing

In [73]:
arr = np.empty((8, 4))

In [74]:
for i in range(8):
    arr[i] = i

In [75]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [76]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [77]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [78]:
arr = np.arange(32).reshape((8, 4))

In [79]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [81]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### Transposing Arrays and Swapping Axes

In [82]:
arr = np.arange(15).reshape((3, 5))

In [83]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [85]:
arr = np.random.randn(6, 3)

In [86]:
arr

array([[-0.46558131,  0.90974406, -0.32690968],
       [ 0.5625897 , -0.04384863,  0.05917592],
       [ 0.81749623,  0.60133116,  0.63612664],
       [ 0.20116749, -0.33649087,  0.50276219],
       [ 1.53614011,  1.29664476, -0.12714641],
       [ 0.22035524,  0.57704734, -0.20811359]])

In [87]:
np.dot(arr.T, arr)

array([[ 3.65032445,  2.09464975,  0.56549172],
       [ 2.09464975,  3.31865349, -0.37160616],
       [ 0.56549172, -0.37160616,  0.82727613]])

In [88]:
arr = np.arange(16).reshape((2, 2, 4))

In [89]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])