[KRITIK AGARWAL 19BBTCS067](https://github.com/Kritik007)

Deep Learning Lab Experiment 1

Basic Operations of Tensor Flow: Implement and demonstrate the basic operations of tensor flow along with printing your name & UG number



---


Tensorflow has gained a lot of attention in the last few years for deep learning models. It provides simple APIs for the creation of neural networks which can be effectively scaled and hosted on different platforms. 

Tensorflow is a python framework that has a comprehensive set of tools and libraries to create machine learning projects. Here the relationship of the tensor with TensorFlow is in the sense that most of the input, intermediate, and output data is in the form of tensors.


---



#### Tensorflow constant and variables

Tensorflow uses its own type of constants and variable also has a different method to declare, define and initialize them. 

In [ ]:
#import tensorflow as tf
import tensorflow as tf

# Declare a constant, we need to import constant from tensorflow
sample_constant = tf.constant(20)
print(sample_constant.dtype)
print("\n")

# Now we can perform some operations using tensorlfow in this constant
# Similarly, we can create variables also
A1=tf.Variable([1,2,3,4])
print(A1)
print("\n")

#Above created variable can be printed using the numpy conversion
print(A1.numpy())
print("\n")

B1=A1.numpy()
B1 = tf.Variable(B1)
print(B1)

<dtype: 'int32'>


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


[1 2 3 4]


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


#### Zeros and Ones

When performing various operations in the working of the neural networks, we have to take matrices with all elements as zero or one initialized. Tensorflow has zeros and ones function that can be used to create them in a single line of code. 

In [ ]:
# Ones function
A1 = tf.ones([3,2], tf.int32)
print(A1.numpy())
print("\n")

# Zeros function
B1 = tf.zeros([3,2])
print(B1)

A1 = tf.constant([1,2,3,4])
A23 = tf.constant([[1,2,3], [4,5,6]])

# create ones tensor and perform element wise multiplication
B1 = tf.ones_like(A1)
B23 = tf.ones_like(A23)

[[1 1]
 [1 1]
 [1 1]]


tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


Apart from ones and zeros, we can also initialize a tensor of any shape with any value using *tf.fill* method.

In [ ]:
# fill method
c33 = tf.fill([3,3], 7)
print(c33.numpy())

[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Operations

Implementation of a neural network using TensorFlow requires various operations to be performed between the constants and the variables.

- Add

In [ ]:
# create two tensors
a1 = tf.fill([3,3], 7)
a2 = tf.fill([3,3], 3)

# Add the two tensors
a3 = tf.add(a1,a2)

# print final tensor
print(a3.numpy())

[[10 10 10]
 [10 10 10]
 [10 10 10]]


- Multiply and Matrix Multiplication

In [ ]:
# Ones function
A1 = tf.ones([3,2], tf.int32)

# create ones tensor and perform element wise multiplication
B1 = tf.ones_like(A1)
C1 = tf.multiply(A1,B1)

# Matrix multiplication
# create feature value
feat_value = tf.constant([[1,12],[2,13],[3,14]])
parameters = tf.constant([[100],[200]])
print(parameters)
print("\n")

# create predictions by matrix multiplication
pred = tf.matmul(feat_value, parameters)
print(pred)
print("\n")

# if we define actual value, we can have errors
actual = [[110], [120],[130]]
error = actual-pred
print(error)

tf.Tensor(
[[100]
 [200]], shape=(2, 1), dtype=int32)


tf.Tensor(
[[2500]
 [2800]
 [3100]], shape=(3, 1), dtype=int32)


tf.Tensor(
[[-2390]
 [-2680]
 [-2970]], shape=(3, 1), dtype=int32)


- Reduce Functions

In [ ]:
# we can reduce the value of tensor
feat_value = tf.constant([[1,12],[2,13],[3,14]])
pred = tf.reduce_sum(feat_value)
print(pred)
print("\n")

# we can reduce at any dimension also
print(tf.reduce_sum(feat_value, 0))     # This is reduce sum for zero dimension means column wise
print("\n")

print(tf.reduce_sum(feat_value, 1))     # This is reduce sum for first dimension means row wise

tf.Tensor(45, shape=(), dtype=int32)


tf.Tensor([ 6 39], shape=(2,), dtype=int32)


tf.Tensor([13 15 17], shape=(3,), dtype=int32)


- Gradient

In [ ]:
# Define x
x = tf.Variable(6.0)

# Define y within instance of GradientTape
with tf.GradientTape() as gt:
  gt.watch(x)
  y = tf.multiply(x, x)
  
#Evaluate the gradient of y at x = 6
g = gt.gradient(y, x)
print(g.numpy())

12.0


- Reshape

In [ ]:
# we need to reshape a picture so that it can be feed to neural network
# lets say we have a 28*28 grayscale image
image = tf.random.uniform([28,28], maxval=255, dtype='int32')
image_reshape = tf.reshape(image, [28*28,1])
# this is required when we input an image to the neural network

- Random Numbers

In [ ]:
g1 = tf.random.Generator.from_seed(1)
print(g1.normal(shape=[2, 3]))
print("\n")

g2 = tf.random.get_global_generator()
print(g2.normal(shape=[2, 3]))
print("\n")

g3 = tf.random.Generator.from_seed(1, alg='philox')
print(g3.normal(shape=[2, 3]))
print("\n")

g = tf.random.Generator.from_non_deterministic_state()
print(g.normal(shape=[2, 3]))

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)


tf.Tensor(
[[ 0.04502168 -1.419444    1.045039  ]
 [ 1.0860493   0.25064045  0.04702757]], shape=(2, 3), dtype=float32)


tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)


tf.Tensor(
[[ 1.3171048  -0.10229805 -0.88267523]
 [ 0.20077606  1.310642    0.09625737]], shape=(2, 3), dtype=float32)


- Losses in Tensorflow

In [ ]:
# Three losses most commonly used
# Mean Absolute Error
# tf.keras.losses.mae()

# Mean squared error
# tf.keras.losses.mse()

# Huber Error
# tf.keras.losses.huber()

print("Kritik Agarwal 19BBTCS067")

Kritik Agarwal 19BBTCS067
